version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.12.1
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:        
    - ./elasticData:/usr/share/elasticsearch/data
  kibana:
    image: kibana:7.12.1
    ports:
      - '5601:5601'